#!/usr/bin/with-contenv bash

DOWNLOAD_PATH=${DOWNLOAD_PATH:-/downloads}

# Download path spec by user may have
# multiple nested internal directories
mkdir -p "${DOWNLOAD_PATH}"
cd "${DOWNLOAD_PATH}" || exit 1
until test "${PWD}" = "/"; do
  chown abc:abc .
  cd ..
done

chown -R abc:abc /config